# Funding options for asdf-ghjk

# GitHub Sponsors
# github: [username]

# Open Collective
# open_collective: asdf-ghjk

# Patreon
# patreon: username

# Custom funding links
# custom: ['https://example.com']

# Note: Update this file if you set up funding options for the project
